version: "3"
services:
  mqtt-python:
    build: .
    restart: always
    ports:
      - "1884:1883"
    volumes:
      - ./app_api:/app_api
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      - MQTT_BROKER=13.40.139.95
      - MQTT_TOPIC=Datos
      - MQTT_PORT=1883
      - MONGODB_HOST=mongodb://user:pass@mongodb:27017/

  mongodb:
    image: mongo:4.4
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/usr/data/db
